#!/usr/bin/env python3
"""
D1 マスターデータ（郵便番号・学校）シードSQL生成スクリプト

  データソース:
    - 日本郵便「住所の郵便番号（1レコード1行, UTF-8形式）」utf_ken_all.zip
    - 文部科学省「学校コード一覧」CSV（東日本(1)(2) / 西日本）

  使い方:
    python3 scripts/build_master_seed.py              # 公式サイトから最新データを取得して生成
    python3 scripts/build_master_seed.py --src DIR    # 取得済みファイル(utf_ken_all.csv / mext_*.csv)を利用

  出力（.gitignore 対象・Pagesの静的配信に含めない）:
    db/seed/zip_codes.sql
    db/seed/schools.sql

  D1 への適用:
    npx wrangler d1 execute okamoshi-master --remote --file=db/seed/zip_codes.sql
    npx wrangler d1 execute okamoshi-master --remote --file=db/seed/schools.sql

  ※ 外部ライブラリ不要（Python 3.8+ 標準ライブラリのみ）
  ※ 文科省CSVのURLは更新のたびに変わるため、年次更新時は MEXT_URLS を差し替えてください。
     https://www.mext.go.jp/b_menu/toukei/mext_01087.html
"""
from __future__ import annotations

import argparse
import csv
import io
import os
import re
import sys
import urllib.request
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "db" / "seed"

KEN_ALL_URL = "https://www.post.japanpost.jp/service/search/zipcode/download/utf/zip/utf_ken_all.zip"
MEXT_URLS = [
    # 令和8年5月1日時点（暫定版）/ 2026-08-25 更新
    "https://www.mext.go.jp/content/20260825-mxt_chousa01-000011635_2-1.csv",  # 東日本(1)
    "https://www.mext.go.jp/content/20260825-mxt_chousa01-000011635_2-2.csv",  # 東日本(2)
    "https://www.mext.go.jp/content/20260825-mxt_chousa01-000011635_4.csv",    # 西日本
]

# 1 INSERT 文あたりの行数（D1 の SQL ステートメント長上限 100KB を十分下回るように）
ROWS_PER_INSERT = 200

PREFECTURES = [
    "北海道", "青森県", "岩手県", "宮城県", "秋田県", "山形県", "福島県",
    "茨城県", "栃木県", "群馬県", "埼玉県", "千葉県", "東京都", "神奈川県",
    "新潟県", "富山県", "石川県", "福井県", "山梨県", "長野県", "岐阜県",
    "静岡県", "愛知県", "三重県", "滋賀県", "京都府", "大阪府", "兵庫県",
    "奈良県", "和歌山県", "鳥取県", "島根県", "岡山県", "広島県", "山口県",
    "徳島県", "香川県", "愛媛県", "高知県", "福岡県", "佐賀県", "長崎県",
    "熊本県", "大分県", "宮崎県", "鹿児島県", "沖縄県",
]

# 文科省 学校種コード → school_type（申込対象: 小6・中1〜中3 に関係する学校種のみ）
SCHOOL_TYPES = {
    "B1": "小学校",
    "C1": "中学校",
    "C2": "義務教育学校",
    "D2": "中等教育学校",
}


# ------------------------------------------------------------
# 共通ユーティリティ
# ------------------------------------------------------------
def fetch(url: str) -> bytes:
    print(f"  ↓ {url}", file=sys.stderr)
    req = urllib.request.Request(url, headers={"User-Agent": "okamoshi-master-seed/1.0"})
    with urllib.request.urlopen(req, timeout=60) as res:
        return res.read()


def sql_str(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def write_inserts(path: Path, table: str, columns: list[str], rows: list[tuple]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as f:
        f.write(f"-- generated by scripts/build_master_seed.py ({len(rows)} rows)\n")
        f.write(f"DELETE FROM {table};\n")
        cols = ", ".join(columns)
        for i in range(0, len(rows), ROWS_PER_INSERT):
            chunk = rows[i:i + ROWS_PER_INSERT]
            values = ",\n".join("(" + ", ".join(sql_str(v) for v in row) + ")" for row in chunk)
            f.write(f"INSERT INTO {table} ({cols}) VALUES\n{values};\n")
    print(f"  ✓ {path.relative_to(ROOT)}  ({len(rows):,} rows)", file=sys.stderr)


# ------------------------------------------------------------
# 郵便番号（日本郵便 KEN_ALL）
# ------------------------------------------------------------
_PAREN_RE = re.compile(r"（.*?）|\(.*?\)")
_NO_TOWN_PATTERNS = (
    "以下に掲載がない場合",
)


def clean_town(town: str) -> str:
    """KEN_ALL の町域名をフォーム自動入力向けに正規化する。"""
    if not town or any(p in town for p in _NO_TOWN_PATTERNS):
        return ""
    # 「○○の次に番地がくる場合」「○○一円」は町域を特定できないので空にする
    if town.endswith("の次に番地がくる場合"):
        return ""
    if town.endswith("一円") and town != "一円":
        return ""
    # 「大通西（１～１９丁目）」「ＪＲタワー（地階・階層不明）」→ 括弧部分を除去
    town = _PAREN_RE.sub("", town)
    # 閉じ括弧が欠けているケースの保険
    town = re.sub(r"（.*$", "", town)
    return town.strip()


def build_zip_codes(ken_all_csv_text: str) -> list[tuple]:
    seen: set[tuple] = set()
    rows: list[tuple] = []
    for rec in csv.reader(io.StringIO(ken_all_csv_text)):
        if len(rec) < 9:
            continue
        zip_code = rec[2].strip()
        if not re.fullmatch(r"\d{7}", zip_code):
            continue
        row = (zip_code, rec[6].strip(), rec[7].strip(), clean_town(rec[8].strip()))
        if row in seen:
            continue
        seen.add(row)
        rows.append(row)
    rows.sort(key=lambda r: r[0])
    return rows


# ------------------------------------------------------------
# 学校（文科省 学校コード）
# ------------------------------------------------------------
def build_schools(csv_texts: list[str]) -> list[tuple]:
    rows: dict[str, tuple] = {}
    for text in csv_texts:
        for rec in csv.reader(io.StringIO(text)):
            if len(rec) < 10 or not re.fullmatch(r"[A-Z]\d{12}", rec[0].strip()):
                continue
            code = rec[0].strip()
            type_code = rec[1].strip()[:2]          # "C1(中学校)" → "C1"
            school_type = SCHOOL_TYPES.get(type_code)
            if not school_type:
                continue
            branch = rec[4].strip()                 # "9(廃)" は廃校
            abolished = rec[9].strip()              # 属性情報廃止年月日
            if branch.startswith("9") or abolished:
                continue
            pref_no = re.match(r"(\d{2})", rec[2].strip())
            if not pref_no:
                continue
            idx = int(pref_no.group(1)) - 1
            if not 0 <= idx < len(PREFECTURES):
                continue
            name = rec[5].strip()
            if not name:
                continue
            rows[code] = (code, name, school_type, PREFECTURES[idx])
    return sorted(rows.values(), key=lambda r: r[0])


# ------------------------------------------------------------
def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--src", help="取得済みデータのディレクトリ（utf_ken_all.csv と MEXT の *.csv）")
    args = ap.parse_args()

    print("[1/2] 郵便番号データ", file=sys.stderr)
    if args.src:
        ken_all_text = Path(args.src, "utf_ken_all.csv").read_text(encoding="utf-8-sig")
    else:
        with zipfile.ZipFile(io.BytesIO(fetch(KEN_ALL_URL))) as zf:
            name = next(n for n in zf.namelist() if n.lower().endswith(".csv"))
            ken_all_text = zf.read(name).decode("utf-8-sig")
    write_inserts(OUT_DIR / "zip_codes.sql", "zip_codes",
                  ["zip_code", "prefecture", "city", "town"], build_zip_codes(ken_all_text))

    print("[2/2] 学校コードデータ", file=sys.stderr)
    if args.src:
        texts = [p.read_text(encoding="utf-8-sig") for p in sorted(Path(args.src).glob("*.csv"))
                 if p.name != "utf_ken_all.csv"]
    else:
        texts = [fetch(u).decode("utf-8-sig") for u in MEXT_URLS]
    write_inserts(OUT_DIR / "schools.sql", "schools",
                  ["school_code", "school_name", "school_type", "prefecture"], build_schools(texts))


if __name__ == "__main__":
    main()
